### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by proesslet** [nixahams/nixahams-website#10]
Got a somewhat working user login system on "usersystem" branch.

Navbar now has a button to open a login modal for users to log in, and then updates the vuex store with that information. Will need to add more functionality such as logout and also make it persist user data across page reloads, but it is progress!

This will allow us to create pages/components that are visible by only certain people

**Comment by proesslet** [comment]
Will need to decide if we want just anybody to create an account, or if we want to integrate that into our dues flow (pay dues -> redirect to create account page)

Some problems with this are that if someone pays in person, they won't be able to then create an account, but we can come up with a fix for that pretty easily. I have a couple ideas for this already, just need to work through the logic

**Comment by proesslet** [comment]
Note to the non-devs: these features are only on the usersystem branch, so they will not be visible on the live site until we are ready to publish them. Here's some photos - Josh had already changed the nav bar to a horizontal style, so I went with that and I think it looks a lot neater and user friendly than the vertical one. Let me know your thoughts!

![Screenshot 2023-06-22 at 7 33 38 PM](https://github.com/nixahams/nixahams-website/assets/10239258/ca71cd09-5ca6-4e37-a7ea-eaa6063eac85)

![Screenshot 2023-06-22 at 7 47 12 PM](https://github.com/nixahams/nixahams-website/assets/10239258/e218e158-21e8-4cd4-afd0-2305fccaec4e)

**Comment by nixahams** [comment]
I like the horizontal bar

**Comment by campjordan** [comment]
Horizontal Bar is nice, might be good to check to see how that affects the banner function.

**Comment by proesslet** [comment]
Yep, just took a bit of restyling to place it below the nav bar, but it still works!

![Screenshot 2023-06-23 at 11 35 31 AM](https://github.com/nixahams/nixahams-website/assets/10239258/7fdc2336-da7b-40a3-926d-0b3b7b4134c5)

**Comment by nixahams** [comment]
I like the horizontal bar also - most people seem to like that vs the vertical so I think that’s a good move.   Probably just what people are used to however.James Adkins, KB0NHX417-834-2745 (Cell)On Jun 23, 2023, at 11:36 AM, 'Preston Roesslet' via k0nxa ***@***.***> wrote:﻿
Yep, just took a bit of restyling to place it below the nav bar, but it still works!

**Comment by proesslet** [comment]
Update on the user system, might soon be ready to push to the live version! Need to do some more testing and some minor modifications to it this week, but it is functional! Also need to make it a little more mobile friendly as well, but that shouldn't take too long

Will need to work out registration logistics. Do y'all want just anybody to be able to register and have an account on the website, or do you want to keep it to just people that have paid dues? 

Right now I have 3 permission levels, user, tech, and admin. User is just general club member, tech is for those with access to repeater control system once we get that going on here, and admin is of course access to the admin pages (not sure where Josh is on those).

**Comment by nixahams** [comment]
This is my 2-cents - subject to El Presidente and the rest of the group's
agreement:

I think it should be limited only to those that are paid club members.  I
like the 3 permission levels you have stated.

James Adkins
417-834-2745 (cell)
Amateur Callsign = KB0NHX
GMRS Callsign = WROQ478
www.nixahams.net
www.smlrs.info

"Raise the standards . . .   If the people lead, eventually the leaders
will follow"

"Those saying it can't be done should get out of the way of those doing it"
- Chinese Proverb

**Comment by proesslet** [comment]
Seems like I got the user system working again and Josh seems to have gotten the admin pages mostly finished up. Should hopefully be able to get this version out very soon!

The admin pages will all have the same look and functionality as before, the only difference is now we are actually running them on our server rather than unsecured endpoints in Mongo, so you may not notice much of a difference visually once we do get this rolled out, but I've attached a screenshot at the bottom anyways.

The great thing about this is that it offers so much flexibility! We'll be able to easily add on new features, incorporate other systems such as the repeater control system eventually, and so much more so be coming up with some ideas that you want to prioritize after this gets released!

**Things that still need to be done**
- [ ] Styling issues such as navbar on mobile view
- [ ] Update navbar to include testing info page
- [ ] Ensure each admin page works
- [ ] Ensure each admin page/endpoint is fully secure
- [ ] Set up a system to create accounts for those that have already paid dues (and also for those that will eventually pay in person). I have some ideas for this :)
- [ ] Set up admin page to change user roles, edit information, etc
- [ ] Set up profile page so people can change their password, update callsign if needed, etc
- [ ] TEST TEST TEST

**Other ideas for improvements (can be done after initial rollout)**
- [ ] Implement 2FA (Auth0 is a free option and widely used)
- [ ] Build statistics page to view yearly or even monthly membership numbers
- [ ] Better organized nets pages (perhaps break it down into digital nets, hf nets, and VHF/UHF analog nets?) and also have a way for people to submit nets they'd like to have on the list

![Screenshot 2023-07-09 at 9 02 06 PM](https://github.com/nixahams/nixahams-website/assets/10239258/d7cf24df-6528-4d2a-93e9-0e0ebc1bd63b)

**Comment by nixahams** [comment]
Looks good to me - thanks for all the work you guys have put into the
site.
I'd like to see the repeater information get pushed out - Josh had talked
about doing something different than the scrolling cards, which is probably
not a bad idea since there are so many to choose from.  Having a list in
order by frequency, PL and Name that a person could quickly locate and then
click on for additional information would be ideal in my opinion.

Keep up the great work!

James Adkins
417-834-2745 (cell)
Amateur Callsign = KB0NHX
GMRS Callsign = WROQ478
www.nixahams.net
www.smlrs.info

"Raise the standards . . .   If the people lead, eventually the leaders
will follow"

"Those saying it can't be done should get out of the way of those doing it"
- Chinese Proverb

**Comment by proesslet** [comment]
Yep, I've been talking to my dad about that and what I'm envisioning right now is a table that can be filtered/sorted by the user and lists the status (pulled from the repeater control system hopefully), frequency, etc, and then each one links to its own about full page with pictures, history, etc

**Comment by nixahams** [comment]
Awesome, thanks!

James Adkins
417-834-2745 (cell)
Amateur Callsign = KB0NHX
GMRS Callsign = WROQ478
www.nixahams.net
www.smlrs.info

"Raise the standards . . .   If the people lead, eventually the leaders
will follow"

"Those saying it can't be done should get out of the way of those doing it"
- Chinese Proverb
