### ISSUE TITLE
Contact form doesn't send to club email

### ISSUE THREAD

**Issue by proesslet** [nixahams/nixahams-website#2]

**Comment by campjordan** [comment]
If you find that it's an SMTP problem of some kind, let me know. I can assist in troubleshooting.

**Comment by proesslet** [comment]
I think the issue may be something with the form that is currently on there. I'm not familiar with it, but josh can speak more on it if he knows what the issue is. It's a 3rd party form service that takes the data from the form, and compiles it into an email and sends it to where ever it is set to go. In our case, it should be sending to the club email, but it doesn't seem to be doing so

I have also been playing around with Nodemailer for some other projects of mine, which would allow us to send emails directly from the club's email. This could be beneficial, as it could send the email from the form both to the radio club email, as well as the person that filled it out, and then when you all go to reply to that person, you can simply reply straight from the email as they will be CC'd on it! This would also allow us to easily send confirmation emails when people pay dues, password reset emails, or whatever other emails we would need to send (automated meeting reminders, Hamfest ticket info, etc)

It seems like a pretty neat library, as it basically allows you to send emails from an existing email rather than having to set-up a mail server like you often have to do with languages such as PHP
