### ISSUE TITLE
Dues button does not work

### ISSUE THREAD

**Issue by proesslet** [nixahams/nixahams-website#3]
The button to pay dues does not work. It seems like it tries to send a request to Stripe, but then nothing happens

**Comment by proesslet** [comment]
Dues button now works, just had to add the nixahams.net domain to our allowed domains on Stripe

Will need to test this now that it's in production and make sure it adds people to the roster

**Comment by campjordan** [comment]
> Dues button now works, just had to add the nixahams.net domain to our allowed domains on Stripe
> 
> Will need to test this now that it's in production and make sure it adds people to the roster

It works.  Processed through card.  DIdn't see automatic posting to roster or any email I had joined.

**Comment by proesslet** [comment]
So dues can be payed now, but then nothing happens from there. Taking a look at this now to see if I can find the issue

We also will probably want to change the payment type on stripe to be a one time payment rather than a subscription (Randy, you tested it the other night so we will want to see how we can cancel your subscription since we don't actually have a cancel button)

**Comment by nixahams** [comment]
Yes, one time payment

**Comment by proesslet** [comment]
I think i almost have a fix for the roster not updating. However, there is some sort of server side error that isn't getting caught/resolved, but I can't tell what it is until I am able to sign into Heroku

Also, the payments have been changed to one time payments, but will need to test them to ensure that they work (it seems like they do in test mode, but I won't truly know until I resolve the server side exception I'm running into)

**Comment by proesslet** [comment]
Some good news! The stripe webhook now works! There's still an issue with it adding the member to the roster, but we now at least have communication between Stripe and our backend!

![Screenshot 2023-06-18 at 2 45 53 PM](https://github.com/nixahams/nixahams-website/assets/10239258/e105e06d-c77f-48d7-966f-147df5d3d805)

It also looks like Stripe allows us to customize our checkout page, so we can include fields such as Callsign or a Yes/No dropdown for being an ARRL member! 

![Screenshot 2023-06-18 at 2 47 21 PM](https://github.com/nixahams/nixahams-website/assets/10239258/9269d596-f4a7-4df4-b122-964e7fbe6b36)

**Comment by nixahams** [comment]
Being able to add the custom fields is great - I don’t know if that’s a new option or not but previously we were told it was not an option.  Either way I’m glad you’ve got Stripe working, the auto database adds will be great.I have an updated spreadsheet with 81 members - do you want me to send that to you?If we can collect callsign, email and phone # is it possible to populate that on our member roster ONLY after a login from a “member” or higher login and leave it hidden from those that don’t login?  If so, that would be a good goal to get to before this November when we generally start taking membership dues for the following calendar yearJames Adkins, KB0NHX417-834-2745 (Cell)On Jun 18, 2023, at 2:49 PM, 'Preston Roesslet' via k0nxa ***@***.***> wrote:﻿
Some good news! The stripe webhook now works! There's still an issue with it adding the member to the roster, but we now at least have communication between Stripe and our backend!

It also looks like Stripe allows us to customize our checkout page, so we can include fields such as Callsign or a Yes/No dropdown for being an ARRL member!

**Comment by proesslet** [comment]
Yeah, feel free to send it to me and I can get it updated!

We can certainly populate specific info on the roster only after log-in! Once we have permission levels set-up, we will be able to protect any pages/content that we want really. 

It would be really nice for the family membership if people could add everyone that is part of that, but it doesn't look like Stripe will allow that much customizability - though we could add that functionality on our own (when someone pays for a family membership, it could redirect them to a page to add their family to the roster after verifying that they paid)

It looks like there is a decent amount of flexibility with Stripe, so it shouldn't be too hard to make customized checkouts for other things such as Hamfest or even the donation page (of course we need to get the log-in system working before we do any of that). It looks like we can even build our own checkout pages utilizing Stripe's API - though I'm not sure of any compliancy regulations that may impact that, so for now it's wise to just use theirs, but something to possibly explore in the future if we find that we do need more flexibility at some point

**Comment by nixahams** [comment]
Being able to make donations and be emailed a receipt was one of the things we relayed to Josh.  Purchasing Hamfest tables & tickets were as well with them being emailed a ticket / receipt for the Hamfest table / admission / super tickets.  He thought that could be done pretty easily - one step at a time.For memberships, getting them added to the roster immediately and sending them a receipt is really important.James Adkins, KB0NHX417-834-2745 (Cell)On Jun 18, 2023, at 3:17 PM, 'Preston Roesslet' via k0nxa ***@***.***> wrote:﻿
Yeah, feel free to send it to me and I can get it updated!
We can certainly populate specific info on the roster only after log-in! Once we have permission levels set-up, we will be able to protect any pages/content that we want really.
It would be really nice for the family membership if people could add everyone that is part of that, but it doesn't look like Stripe will allow that much customizability - though we could add that functionality on our own (when someone pays for a family membership, it could redirect them to a page to add their family to the roster after verifying that they paid)
It looks like there is a decent amount of flexibility with Stripe, so it shouldn't be too hard to make customized checkouts for other things such as Hamfest or even the donation page (of course we need to get the log-in system working before we do any of that). It looks like we can even build our own checkout pages utilizing Stripe's API - though I'm not sure of any compliancy regulations that may impact that, so for now it's wise to just use theirs, but something to possibly explore in the future if we find that we do need more flexibility at some point

**Comment by proesslet** [comment]
Yeah, emailing a receipt will be super easy. I do need to get with Randy on that and see if we can set-up the club email using Nodemailer (a Node.JS library). I set it up the other night using my gmail and it only took me about 5 minutes to get an email sent from a Node.JS server. Though I think the club uses outlook if I remember correctly, but even if it is gmail, since it has a custom domain and not @gmail.com, I'm not sure how that would work

Once we have that (or another email option) working, we'll be able to send receipts very easily. In fact, we'll be able to send whatever automated emails we want at that point (meeting reminders, repeater status change once we get that linked in, etc)

**Comment by nixahams** [comment]
I sounds great.   Randy will have the answers on the email.   The Repeater a council just moved to Microsoft for email as our original email server had been blacklisted and people weren’t getting emails.   Having a way to email everyone outside of the groups.it was a goal as well in case groups.Jo goes away / becomes costly, etc.  new members would get added to the distribution list.   Sounds like you’re thinking about some of the same stuff we talked about.James Adkins, KB0NHX417-834-2745 (Cell)On Jun 18, 2023, at 3:31 PM, 'Preston Roesslet' via k0nxa ***@***.***> wrote:﻿
Yeah, emailing a receipt will be super easy. I do need to get with Randy on that and see if we can set-up the club email using Nodemailer (a Node.JS library). I set it up the other night using my gmail and it only took me about 5 minutes to get an email sent from a Node.JS server. Though I think the club uses outlook if I remember correctly, but even if it is gmail, since it has a custom domain and not @gmail.com, I'm not sure how that would work
Once we have that (or another email option) working, we'll be able to send receipts very easily. In fact, we'll be able to send whatever automated emails we want at that point (meeting reminders, repeater status change once we get that linked in, etc)

**Comment by proesslet** [comment]
Yeah, once we have an email linked in with our server, we could potentially do whatever we want with it. I hadn't thought about replacing Groups.io, but that would certainly be an option! 

That may be a bigger task, I'm not sure of the ins and outs of email lists and such, but at least short term we could set-up a way for you all to send emails to everybody that has a website account for sure

**Comment by nixahams** [comment]
Don’t want to replace it, but be prepared if / when it goes away to still be able to email membersJames Adkins, KB0NHX417-834-2745 (Cell)On Jun 18, 2023, at 3:47 PM, 'Preston Roesslet' via k0nxa ***@***.***> wrote:﻿
Yeah, once we have an email linked in with our server, we could potentially do whatever we want with it. I hadn't thought about replacing Groups.io, but that would certainly be an option!
That may be a bigger task, I'm not sure of the ins and outs of email lists and such, but at least short term we could set-up a way for you all to send emails to everybody that has a website account for sure

**Comment by proesslet** [comment]
Gotcha, yeah, that should be super easy then!

**Comment by proesslet** [comment]
It works! Needs some fine tuning to add the correct information, but it works!

Had to temporarily allow connections from anywhere to Mongo, so we will want to look into this. I've had it working on another project of mine and I don't believe 'anywhere access' was enabled for that one, but it's been a while so I'm not sure. Anywhere connections should not be a huge issue as our connection URL is private and it still has standard password protection and 2FA, but it could definitely be a potential security risk should any of our credentials somehow be made public. Of course, if we end up moving over to a SQL database as Josh and I talked about a couple times, then we won't have to worry about this at all (seems like another reason to support switching to SQL)

**Comment by proesslet** [comment]
Dues button now works, and ~should~ automatically add the member to the roster - worked for me locally, but won't know it works 100% on the live version until somebody does it
